/*@@ Generated by Wedit @@ */
#include <windows.h>
#include <lfc.h>
#include "clickoffres.h"

/*@@Callbacks Section--------------------------------------Callbacks Section@@*/
/*@@Dialog "Dlg100"------------------------------------------Dialog "Dlg100"@@*/
static ST_DIALOGBOX *Set_Dlg100_Fields(HWND hwnd)
{
	struct _Dlg100 *s;
	ST_DIALOGBOX *std = GetSTControlFromHwnd(hwnd);
	s = malloc(sizeof(struct _Dlg100));
	s->id_itext = GetControl(std,105);
	s->id_active = GetControl(std,114);
	s->id_remove = GetControl(std,112);
	s->ctrl110 = GetControl(std,110);
	s->id_list = GetControl(std,102);
	s->id_advanced = GetControl(std,113);
	s->id_close = GetControl(std,103);
	s->id_exit = GetControl(std,101);
	s->hwnd = hwnd;
	std->Data->pDlgStruct = s;
	return std;
}

BOOL APIENTRY Dlg100(HWND hwnd,UINT msg,WPARAM wParam,LPARAM lParam)
{
	static HFONT DialogFont;
	ST_DIALOGBOX *std;
	struct _Dlg100 *s;
	
	std = GetSTControlFromHwnd(hwnd);
	if (std && std->Data)
	{
		s = std->Data->pDlgStruct;
		if (s)
		{
			s->wParam = wParam;
			s->lParam = lParam;
		}
	}
	switch(msg)
	{
		case WM_INITDIALOG:
			/* Initialization of the dialog box */
			DialogFont = SetDialogFont(hwnd,"MS Sans Serif",8,400);
			CenterWindow(hwnd,1);
			std = ST_InitDialogBox(hwnd);
			Set_Dlg100_Fields(hwnd);
			if (!(std && std->Data)) break;
			s = std->Data->pDlgStruct;
			if (!s) break;
			Dlg100Init(std,s);
			break;
		case WM_COMMAND:
			switch (LOWORD(wParam))
			{
				case ID_REMOVE:
					Dlg100Push_button112Selected(GetControl(std,112),s);
				break;
				case ID_ADVANCED:
					Dlg100Push_button113Selected(GetControl(std,113),s);
				break;
				case ID_CLOSE:
					Dlg100Push_button103Selected(GetControl(std,103),s);
				break;
				case ID_EXIT:
					Dlg100Push_button101Selected(GetControl(std,101),s);
				break;
			}
			break;
		case WM_DESTROY:
			DeleteObject(DialogFont);
			/* Remove the input arguments property */
			RemoveProp(hwnd,"InputArgument");
			break;
		case WM_NCDESTROY:
			ST_DestroyDialogBox(hwnd);
			break;
	}
	return(HandleDefaultMessages(hwnd,msg,wParam,lParam));
}
int RunDlg100(HWND parent)
{
	return DialogBox((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(100),parent,Dlg100);
}
HWND StartDlg100(HWND parent)
{
	return CreateDialog((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(100),parent,Dlg100);
}
/*@@Dialog "Dlg300"------------------------------------------Dialog "Dlg300"@@*/
static ST_DIALOGBOX *Set_Dlg300_Fields(HWND hwnd)
{
	struct _Dlg300 *s;
	ST_DIALOGBOX *std = GetSTControlFromHwnd(hwnd);
	s = malloc(sizeof(struct _Dlg300));
	s->ctrl302 = GetControl(std,302);
	s->ctrl303 = GetControl(std,303);
	s->ctrl314 = GetControl(std,314);
	s->ctrl308 = GetControl(std,308);
	s->id_showdoc = GetControl(std,304);
	s->id_email = GetControl(std,305);
	s->ctrl307 = GetControl(std,307);
	s->ctrl309 = GetControl(std,309);
	s->ctrl310 = GetControl(std,310);
	s->ctrl311 = GetControl(std,311);
	s->ctrl312 = GetControl(std,312);
	s->id_clicksum = GetControl(std,313);
	s->hwnd = hwnd;
	std->Data->pDlgStruct = s;
	return std;
}

BOOL APIENTRY Dlg300(HWND hwnd,UINT msg,WPARAM wParam,LPARAM lParam)
{
	static HFONT DialogFont;
	ST_DIALOGBOX *std;
	struct _Dlg300 *s;
	
	std = GetSTControlFromHwnd(hwnd);
	if (std && std->Data)
	{
		s = std->Data->pDlgStruct;
		if (s)
		{
			s->wParam = wParam;
			s->lParam = lParam;
		}
	}
	switch(msg)
	{
		case WM_INITDIALOG:
			/* Initialization of the dialog box */
			DialogFont = SetDialogFont(hwnd,"MS Sans Serif",8,400);
			CenterWindow(hwnd,1);
			std = ST_InitDialogBox(hwnd);
			Set_Dlg300_Fields(hwnd);
			if (!(std && std->Data)) break;
			s = std->Data->pDlgStruct;
			if (!s) break;
			Dlg300Init(std,s);
			break;
		case WM_COMMAND:
			switch (LOWORD(wParam))
			{
				case ID_SHOWDOC:
					Dlg300Push_button304Selected(GetControl(std,304),s);
				break;
				case ID_EMAIL:
					Dlg300Push_button305Selected(GetControl(std,305),s);
				break;
			}
			break;
		case WM_DESTROY:
			DeleteObject(DialogFont);
			/* Remove the input arguments property */
			RemoveProp(hwnd,"InputArgument");
			break;
		case WM_NCDESTROY:
			ST_DestroyDialogBox(hwnd);
			break;
	}
	return(HandleDefaultMessages(hwnd,msg,wParam,lParam));
}
int RunDlg300(HWND parent)
{
	return DialogBox((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(300),parent,Dlg300);
}
HWND StartDlg300(HWND parent)
{
	return CreateDialog((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(300),parent,Dlg300);
}
/*@@Dialog "Dlg500"------------------------------------------Dialog "Dlg500"@@*/
static ST_DIALOGBOX *Set_Dlg500_Fields(HWND hwnd)
{
	struct _Dlg500 *s;
	ST_DIALOGBOX *std = GetSTControlFromHwnd(hwnd);
	s = malloc(sizeof(struct _Dlg500));
	s->ctrl518 = GetControl(std,518);
	s->id_windowtitle = GetControl(std,519);
	s->id_staticbtext = GetControl(std,521);
	s->id_buttontext = GetControl(std,522);
	s->ctrl507 = GetControl(std,507);
	s->id_neverclick = GetControl(std,508);
	s->id_alwaysclick = GetControl(std,509);
	s->id_clickwhentext = GetControl(std,510);
	s->id_msgtext = GetControl(std,506);
	s->ctrl513 = GetControl(std,513);
	s->id_clickoffmethod = GetControl(std,512);
	s->ctrl501 = GetControl(std,501);
	s->id_nodelay = GetControl(std,502);
	s->id_predelay = GetControl(std,520);
	s->id_postdelay = GetControl(std,525);
	s->ctrl526 = GetControl(std,526);
	s->id_delay = GetControl(std,523);
	s->ctrl524 = GetControl(std,524);
	s->ctrl515 = GetControl(std,515);
	s->id_clicknumber = GetControl(std,516);
	s->ctrl517 = GetControl(std,517);
	s->id_cancel = GetControl(std,503);
	s->id_ok = GetControl(std,504);
	s->id_clickonce = GetControl(std,514);
	s->hwnd = hwnd;
	std->Data->pDlgStruct = s;
	return std;
}

BOOL APIENTRY Dlg500(HWND hwnd,UINT msg,WPARAM wParam,LPARAM lParam)
{
	static HFONT DialogFont;
	ST_DIALOGBOX *std;
	struct _Dlg500 *s;
	
	std = GetSTControlFromHwnd(hwnd);
	if (std && std->Data)
	{
		s = std->Data->pDlgStruct;
		if (s)
		{
			s->wParam = wParam;
			s->lParam = lParam;
		}
	}
	switch(msg)
	{
		case WM_INITDIALOG:
			/* Initialization of the dialog box */
			DialogFont = SetDialogFont(hwnd,"MS Sans Serif",8,400);
			CenterWindow(hwnd,1);
			std = ST_InitDialogBox(hwnd);
			Set_Dlg500_Fields(hwnd);
			if (!(std && std->Data)) break;
			s = std->Data->pDlgStruct;
			if (!s) break;
			Dlg500Init(std,s);
			break;
		case WM_COMMAND:
			switch (LOWORD(wParam))
			{
				case ID_WINDOWTITLE:
				break;
				case ID_BUTTONTEXT:
				break;
				case ID_MSGTEXT:
				break;
				case ID_DELAY:
				break;
				case ID_CANCEL:
					Dlg500Push_button503Selected(GetControl(std,503),s);
				break;
				case ID_OK:
					Dlg500Push_button504Selected(GetControl(std,504),s);
				break;
			}
			break;
		case WM_DESTROY:
			DeleteObject(DialogFont);
			/* Remove the input arguments property */
			RemoveProp(hwnd,"InputArgument");
			break;
		case WM_NCDESTROY:
			ST_DestroyDialogBox(hwnd);
			break;
	}
	return(HandleDefaultMessages(hwnd,msg,wParam,lParam));
}
int RunDlg500(HWND parent)
{
	return DialogBox((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(500),parent,Dlg500);
}
HWND StartDlg500(HWND parent)
{
	return CreateDialog((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(500),parent,Dlg500);
}
/*@@Dialog "Dlg200"------------------------------------------Dialog "Dlg200"@@*/
static ST_DIALOGBOX *Set_Dlg200_Fields(HWND hwnd)
{
	struct _Dlg200 *s;
	ST_DIALOGBOX *std = GetSTControlFromHwnd(hwnd);
	s = malloc(sizeof(struct _Dlg200));
	s->id_ok = GetControl(std,504);
	s->ctrl201 = GetControl(std,201);
	s->id_lang = GetControl(std,905);
	s->id_common = GetControl(std,202);
	s->hwnd = hwnd;
	std->Data->pDlgStruct = s;
	return std;
}

BOOL APIENTRY Dlg200(HWND hwnd,UINT msg,WPARAM wParam,LPARAM lParam)
{
	static HFONT DialogFont;
	ST_DIALOGBOX *std;
	struct _Dlg200 *s;
	
	std = GetSTControlFromHwnd(hwnd);
	if (std && std->Data)
	{
		s = std->Data->pDlgStruct;
		if (s)
		{
			s->wParam = wParam;
			s->lParam = lParam;
		}
	}
	switch(msg)
	{
		case WM_INITDIALOG:
			/* Initialization of the dialog box */
			DialogFont = SetDialogFont(hwnd,"MS Sans Serif",8,400);
			CenterWindow(hwnd,1);
			std = ST_InitDialogBox(hwnd);
			Set_Dlg200_Fields(hwnd);
			if (!(std && std->Data)) break;
			s = std->Data->pDlgStruct;
			if (!s) break;
			Dlg200Init(std,s);
			break;
		case WM_COMMAND:
			switch (LOWORD(wParam))
			{
				case ID_OK:
					Dlg200Push_button504Selected(GetControl(std,504),s);
				break;
			}
			break;
		case WM_DESTROY:
			DeleteObject(DialogFont);
			/* Remove the input arguments property */
			RemoveProp(hwnd,"InputArgument");
			break;
		case WM_NCDESTROY:
			ST_DestroyDialogBox(hwnd);
			break;
	}
	return(HandleDefaultMessages(hwnd,msg,wParam,lParam));
}
int RunDlg200(HWND parent)
{
	return DialogBox((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(200),parent,Dlg200);
}
HWND StartDlg200(HWND parent)
{
	return CreateDialog((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(200),parent,Dlg200);
}
/*@@Dialog "Dlg900"------------------------------------------Dialog "Dlg900"@@*/
static ST_DIALOGBOX *Set_Dlg900_Fields(HWND hwnd)
{
	struct _Dlg900 *s;
	ST_DIALOGBOX *std = GetSTControlFromHwnd(hwnd);
	s = malloc(sizeof(struct _Dlg900));
	s->ctrl902 = GetControl(std,902);
	s->ctrl904 = GetControl(std,904);
	s->ctrl911 = GetControl(std,911);
	s->ctrl912 = GetControl(std,912);
	s->id_scantime = GetControl(std,915);
	s->ctrl907 = GetControl(std,907);
	s->ctrl908 = GetControl(std,908);
	s->id_lang = GetControl(std,905);
	s->id_ok = GetControl(std,504);
	s->id_cancel = GetControl(std,503);
	s->hwnd = hwnd;
	std->Data->pDlgStruct = s;
	return std;
}

BOOL APIENTRY Dlg900(HWND hwnd,UINT msg,WPARAM wParam,LPARAM lParam)
{
	static HFONT DialogFont;
	ST_DIALOGBOX *std;
	struct _Dlg900 *s;
	
	std = GetSTControlFromHwnd(hwnd);
	if (std && std->Data)
	{
		s = std->Data->pDlgStruct;
		if (s)
		{
			s->wParam = wParam;
			s->lParam = lParam;
		}
	}
	switch(msg)
	{
		case WM_INITDIALOG:
			/* Initialization of the dialog box */
			DialogFont = SetDialogFont(hwnd,"MS Sans Serif",8,400);
			CenterWindow(hwnd,1);
			std = ST_InitDialogBox(hwnd);
			Set_Dlg900_Fields(hwnd);
			if (!(std && std->Data)) break;
			s = std->Data->pDlgStruct;
			if (!s) break;
			Dlg900Init(std,s);
			break;
		case WM_COMMAND:
			switch (LOWORD(wParam))
			{
				case ID_SCANTIME:
				break;
				case ID_OK:
					Dlg900Push_button504Selected(GetControl(std,504),s);
				break;
				case ID_CANCEL:
					Dlg900Push_button503Selected(GetControl(std,503),s);
				break;
			}
			break;
		case WM_DESTROY:
			DeleteObject(DialogFont);
			/* Remove the input arguments property */
			RemoveProp(hwnd,"InputArgument");
			break;
		case WM_NCDESTROY:
			ST_DestroyDialogBox(hwnd);
			break;
	}
	return(HandleDefaultMessages(hwnd,msg,wParam,lParam));
}
int RunDlg900(HWND parent)
{
	return DialogBox((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(900),parent,Dlg900);
}
HWND StartDlg900(HWND parent)
{
	return CreateDialog((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(900),parent,Dlg900);
}
/*@@Dialog "Dlg400"------------------------------------------Dialog "Dlg400"@@*/
static ST_DIALOGBOX *Set_Dlg400_Fields(HWND hwnd)
{
	struct _Dlg400 *s;
	ST_DIALOGBOX *std = GetSTControlFromHwnd(hwnd);
	s = malloc(sizeof(struct _Dlg400));
	s->hwnd = hwnd;
	std->Data->pDlgStruct = s;
	return std;
}

BOOL APIENTRY Dlg400(HWND hwnd,UINT msg,WPARAM wParam,LPARAM lParam)
{
	static HFONT DialogFont;
	ST_DIALOGBOX *std;
	struct _Dlg400 *s;
	
	std = GetSTControlFromHwnd(hwnd);
	if (std && std->Data)
	{
		s = std->Data->pDlgStruct;
		if (s)
		{
			s->wParam = wParam;
			s->lParam = lParam;
		}
	}
	switch(msg)
	{
		case WM_INITDIALOG:
			/* Initialization of the dialog box */
			DialogFont = SetDialogFont(hwnd,"MS Sans Serif",8,400);
			CenterWindow(hwnd,1);
			std = ST_InitDialogBox(hwnd);
			Set_Dlg400_Fields(hwnd);
			if (!(std && std->Data)) break;
			s = std->Data->pDlgStruct;
			if (!s) break;
			Dlg400Init(std,s);
			break;
		case WM_COMMAND:
			break;
		case WM_DESTROY:
			DeleteObject(DialogFont);
			/* Remove the input arguments property */
			RemoveProp(hwnd,"InputArgument");
			break;
		case WM_NCDESTROY:
			ST_DestroyDialogBox(hwnd);
			break;
	}
	return(HandleDefaultMessages(hwnd,msg,wParam,lParam));
}
int RunDlg400(HWND parent)
{
	return DialogBox((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(400),parent,Dlg400);
}
HWND StartDlg400(HWND parent)
{
	return CreateDialog((HANDLE)GetWindowLong(parent,GWL_HINSTANCE),MAKEINTRESOURCE(400),parent,Dlg400);
}
